const rimraf = require("rimraf");
module.exports = api => {
  // 添加新的依赖
  api.extendPackage({
    dependencies: {
      "form-generator-iview": "^0.0.11",
      axios: "^0.18.0",
      iview: "^3.4.0",
      vuex: "^3.1.1",
      "vue-router": "^3.0.6"
    }
  });

  api.render("./template");

  // delete some files generated by built-in plugin
  api.onCreateComplete(() => {
    rimraf.sync(api.resolve("src/router.js"));
    rimraf.sync(api.resolve("src/components/HelloWorld.vue"));
  });
};
